hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function(files)
    hs.reload()
end):start()


hs.hotkey.bind({"ctrl", "cmd"}, "1", function()
	hs.application.launchOrFocusByBundleID("com.openai.atlas")
end)
hs.hotkey.bind({"ctrl", "cmd"}, "2", function()
    hs.application.launchOrFocus("Ghostty")
end)
hs.hotkey.bind({"ctrl", "cmd"}, "3", function()
    hs.application.launchOrFocus("Obsidian")
end)
hs.hotkey.bind({"ctrl", "cmd"}, "4", function()
	hs.application.launchOrFocus("Slack")
end)
hs.hotkey.bind({"ctrl", "cmd"}, "5", function()
	hs.application.launchOrFocus("Wezterm")
end)
