theme = "tokyonight"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner","separator", "version-control", "separator", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = " │ "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
