require('plugins/packer')
require('settings')
require('plugins/nvim-tree')
require('plugins/treesitter')
require('plugins/telescope')
require('plugins/lualine')
require('plugins/dashboard')
require('plugins/blamer')
require('coc/init')
require('keymap')

