[env]

[plugins]

[tasks."yarn:latest"]
description = 'set yarn version to latest'
run = "yarn set version latest"

[tasks."lint:eslint"] # using a ":" means we need to add quotes
run = "eslint ."
[tasks."lint:prettier"]
run = "prettier --check ."
[tasks.lint]
depends = ["lint:*"]

[tasks."typst:live"]
description = "Run typst in watch mode with generating pdf automatically"
run = "~/.config/mise/tasks/typst"

[tasks."monthly_plan"]
description = "Open monthly plan markdown file"
run = "~/.config/mise/tasks/generate_monthly_plan this-month"

[tasks."monthly_plan:next"]
description = "Open monthly plan markdown file"
run = "~/.config/mise/tasks/generate_monthly_plan next-month"

[tasks."todoist"]
description = "Open todoist api client wrapper cli"
run = "~/.config/mise/tasks/3rdparty/todoist"

[tasks."gh"]
description = "Open Github CLI wrapper CLI"
run = "~/.config/mise/tasks/3rdparty/gh"

[tasks."pomo"]
description = "Generate pomodoro timer reminder for Todoist"
run = "~/.config/mise/tasks/pomodoro generate"

[settings]
experimental = true

[tools]
zoxide = "0.9.4"

