# /home/kodingwarrior/.config/tmuxinator/default.yml

name: default
root: ~/

windows:
  - editor:
      layout: main-vertical
      pre: cd ~/kojima-wiki/ &&
        export NEOVIM_THEME=nordic &&
        export ZETTELKASTEN_TARGET="private_wiki" &&
        tmux setenv ZETTELKASTEN_TARGET $ZETTELKASTEN_TARGET
      panes:
        - ruby -rdate -e "date = Date.today; year=date.year.to_s; month=date.month.to_s.rjust(2, '0'); monthly=\"#{year}-#{month}\"; system(\"nvim -O planner/#{monthly}.md monthly/#{monthly}.md\")"
